notifications:
  global:
    irc:
    - openttd
    - openttd.notice

  push:
    only:
    - main
    only-by:
    - survey-summary\[bot\]
  pull-request:
    except-by:
    - dependabot\[bot\]
  issue:
  tag-created:
