name = "openttd-survey-participate"
main = "src/index.js"
compatibility_date = "2024-01-04"

[[r2_buckets]]
binding = 'SURVEY_BUCKET'
bucket_name = 'survey-prod'
preview_bucket_name = 'survey-preview'

[vars]
JWT_KID = "1"
